<?php

return [
    '{{website_url}}' => 'The URL of the website',
    '{{name}}' => 'User\'s full name',
    '{{username}}' => 'User\'s username',
    '{{password}}' => 'User\'s password',
    '{{url}}' => 'URL of the resource',
    '{{otp}}' => 'Email OTP',
    '{{logo}}' => 'Logo URL',
    '{{contact}}' => 'Contact information',
    '{{reply_email}}' => 'Email address for replies',
    '{{downloadurl}}' => 'Download URL',
    '{{invoiceurl}}' => 'Invoice URL',
    '{{product}}' => 'Product information',
    '{{number}}' => 'Product number',
    '{{expiry}}' => 'Expiry date',
    '{{serialkeyurl}}' => 'Serial key URL',
    '{{knowledge_base}}' => 'Knowledge base URL',
    '{{orderHeading}}' => 'Order heading information',
    '{{deletionDate}}' => 'Deletion date information',
    '{{manager_first_name}}' => 'Manager\'s first name',
    '{{manager_last_name}}' => 'Manager\'s last name',
    '{{manager_email}}' => 'Manager\'s email',
    '{{manager_code}}' => 'Manager\'s code',
    '{{manager_mobile}}' => 'Manager\'s mobile number',
    '{{manager_skype}}' => 'Manager\'s Skype ID',
    '{{future_expiry}}' => 'Future expiry information',
    '{{message}}' => 'Message information',
    '{{title}}' => 'Title information',
    '{{company_email}}' => 'Company email address',
    '{{total}}' => 'Total Amount',
    '{{email}}' => 'User\'s email',
    '{{mobile}}' => 'User\'s mobile',
    '{{ip_address}}' => 'User\'s ip_address',
    '{{request_url}}' => 'User\'s request_url',
    '{{contact-us}}' => 'User\'s contact_us',
    '{{product_type}}' => 'User\'s product_type',
    '{{address}}' => 'address information',
    '{{content}}' => 'content',
    '{{currency}}' => 'currency information',
    '{{renewPrice}}' => 'renewPrice information',
    '{{exception}}' => 'exception information',
    '{{expiry_date}}' => 'expiry date for subscription creation link',
    '{{application_title}}' => 'company\'s application title',
    '{{company_title}}' => 'company title',
    '{{licenseCode}}' => 'Order\'s licenseCode',
    '{{date}}' => 'Order\'s expiry date',

];
